/*
 * Generated by MTK SP DrvGen Version 03.13.6  for MT6582. Copyright MediaTek Inc. (C) 2013.
 * Wed May 24 14:45:51 2017
 * Do Not Modify the File.
 */

#define GPIO_DVDD28_MSDC1     GPIO_VIO28
#define GPIO_DVDD28_MSDC2     GPIO_VIO18
#define GPIO_DVDD28_BPI     GPIO_VIO18


